const suppliersTable = [
  {
    name: "ABC Furniture",
    contractName: "John Doe",
    email: "johndoe@gmail.com",
    phone: "+8618056754632",
    wechat: "+8618056754632",
    category: "Furniture, USB",
    addressess: "-",
    ODM: "yes",
    address: "Gaundong",
    sampleLeadTime: "14 days",
    supplierReturnDate: "20/08/2022",
    supplierType: "Asset Tracker, Purchase, Repair...",
    allowCurrency: "US",
  },

  {
    name: "ABC Furniture",
    contractName: "John Doe",
    email: "johndoe@gmail.com",
    phone: "+8618056754632",
    wechat: "+8618056754632",
    category: "Furniture, USB",
    addressess: "-",
    ODM: "yes",
    address: "Gaundong",
    sampleLeadTime: "14 days",
    supplierReturnDate: "20/08/2022",
    supplierType: "Asset Tracker, Purchase, Repair...",
    allowCurrency: "US",
  },

  {
    name: "ABC Furniture",
    contractName: "John Doe",
    email: "johndoe@gmail.com",
    phone: "+8618056754632",
    wechat: "+8618056754632",
    category: "Furniture, USB",
    addressess: "-",
    ODM: "yes",
    address: "Gaundong",
    sampleLeadTime: "14 days",
    supplierReturnDate: "20/08/2022",
    supplierType: "Asset Tracker, Purchase, Repair...",
    allowCurrency: "US",
  },

  {
    name: "ABC Furniture",
    contractName: "John Doe",
    email: "johndoe@gmail.com",
    phone: "+8618056754632",
    wechat: "+8618056754632",
    category: "Furniture, USB",
    addressess: "-",
    ODM: "yes",
    address: "Gaundong",
    sampleLeadTime: "14 days",
    supplierReturnDate: "20/08/2022",
    supplierType: "Asset Tracker, Purchase, Repair...",
    allowCurrency: "US",
  },

  {
    name: "ABC Furniture",
    contractName: "John Doe",
    email: "johndoe@gmail.com",
    phone: "+8618056754632",
    wechat: "+8618056754632",
    category: "Furniture, USB",
    addressess: "-",
    ODM: "yes",
    address: "Gaundong",
    sampleLeadTime: "14 days",
    supplierReturnDate: "20/08/2022",
    supplierType: "Asset Tracker, Purchase, Repair...",
    allowCurrency: "US",
  },

  {
    name: "ABC Furniture",
    contractName: "John Doe",
    email: "johndoe@gmail.com",
    phone: "+8618056754632",
    wechat: "+8618056754632",
    category: "Furniture, USB",
    addressess: "-",
    ODM: "yes",
    address: "Gaundong",
    sampleLeadTime: "14 days",
    supplierReturnDate: "20/08/2022",
    supplierType: "Asset Tracker, Purchase, Repair...",
    allowCurrency: "US",
  },

  {
    name: "ABC Furniture",
    contractName: "John Doe",
    email: "johndoe@gmail.com",
    phone: "+8618056754632",
    wechat: "+8618056754632",
    category: "Furniture, USB",
    addressess: "-",
    ODM: "yes",
    address: "Gaundong",
    sampleLeadTime: "14 days",
    supplierReturnDate: "20/08/2022",
    supplierType: "Asset Tracker, Purchase, Repair...",
    allowCurrency: "US",
  },

  {
    name: "ABC Furniture",
    contractName: "John Doe",
    email: "johndoe@gmail.com",
    phone: "+8618056754632",
    wechat: "+8618056754632",
    category: "Furniture, USB",
    addressess: "-",
    ODM: "yes",
    address: "Gaundong",
    sampleLeadTime: "14 days",
    supplierReturnDate: "20/08/2022",
    supplierType: "Asset Tracker, Purchase, Repair...",
    allowCurrency: "US",
  },

  {
    name: "ABC Furniture",
    contractName: "John Doe",
    email: "johndoe@gmail.com",
    phone: "+8618056754632",
    wechat: "+8618056754632",
    category: "Furniture, USB",
    addressess: "-",
    ODM: "yes",
    address: "Gaundong",
    sampleLeadTime: "14 days",
    supplierReturnDate: "20/08/2022",
    supplierType: "Asset Tracker, Purchase, Repair...",
    allowCurrency: "US",
  },

  {
    name: "ABC Furniture",
    contractName: "John Doe",
    email: "johndoe@gmail.com",
    phone: "+8618056754632",
    wechat: "+8618056754632",
    category: "Furniture, USB",
    addressess: "-",
    ODM: "yes",
    address: "Gaundong",
    sampleLeadTime: "14 days",
    supplierReturnDate: "20/08/2022",
    supplierType: "Asset Tracker, Purchase, Repair...",
    allowCurrency: "US",
  },

  {
    name: "ABC Furniture",
    contractName: "John Doe",
    email: "johndoe@gmail.com",
    phone: "+8618056754632",
    wechat: "+8618056754632",
    category: "Furniture, USB",
    addressess: "-",
    ODM: "yes",
    address: "Gaundong",
    sampleLeadTime: "14 days",
    supplierReturnDate: "20/08/2022",
    supplierType: "Asset Tracker, Purchase, Repair...",
    allowCurrency: "US",
  },

  {
    name: "ABC Furniture",
    contractName: "John Doe",
    email: "johndoe@gmail.com",
    phone: "+8618056754632",
    wechat: "+8618056754632",
    category: "Furniture, USB",
    addressess: "-",
    ODM: "yes",
    address: "Gaundong",
    sampleLeadTime: "14 days",
    supplierReturnDate: "20/08/2022",
    supplierType: "Asset Tracker, Purchase, Repair...",
    allowCurrency: "US",
  },

  {
    name: "ABC Furniture",
    contractName: "John Doe",
    email: "johndoe@gmail.com",
    phone: "+8618056754632",
    wechat: "+8618056754632",
    category: "Furniture, USB",
    addressess: "-",
    ODM: "yes",
    address: "Gaundong",
    sampleLeadTime: "14 days",
    supplierReturnDate: "20/08/2022",
    supplierType: "Asset Tracker, Purchase, Repair...",
    allowCurrency: "US",
  },
];

export default suppliersTable;
